### ISSUE TITLE
support for ~/.config/i3/config ???

### ISSUE THREAD

**Issue by bhepple** [talwrii/i3parse#1]
My distro (fedora-27) expects the i3 config file in ~/.config/i3/config - looks like i3parse can't grok that.

`
0 08:52 ~/ $ i3parse 
usage: i3parse [-h] {free,modes,mode-graph,validate,bindings} ...
i3parse: error: too few arguments
0 08:52 ~/ $ i3parse free
usage: i3parse free [-h] [--mode MODE] [--shift] [--control] [--mod1]
                    [--file [FILE]]
                    letters
i3parse free: error: too few arguments
0 08:52 ~/ $ i3parse free letters
Traceback (most recent call last):
  File "/bin/i3parse", line 11, in <module>
    load_entry_point('i3parse==0.1.0', 'console_scripts', 'i3parse')()
  File "/usr/lib/python2.7/site-packages/i3parse/i3parse.py", line 146, in main
    with open(args.file) as stream:
IOError: [Errno 2] No such file or directory: '/home/bhepple/.i3/config'
0 08:52 ~/ $ ll /home/bhepple/.i3/config
ls: cannot access '/home/bhepple/.i3/config': No such file or directory
0 08:52 ~/ $ i3parse free letters --file .config/i3/config 
Traceback (most recent call last):
  File "/bin/i3parse", line 11, in <module>
    load_entry_point('i3parse==0.1.0', 'console_scripts', 'i3parse')()
  File "/usr/lib/python2.7/site-packages/i3parse/i3parse.py", line 148, in main
    ast = parse(input_string)
  File "/usr/lib/python2.7/site-packages/i3parse/i3parse.py", line 290, in parse
    return grammar.parse(input_string)
  File "/usr/lib/python2.7/site-packages/parsimonious/grammar.py", line 115, in parse
    return self.default_rule.parse(text, pos=pos)
  File "/usr/lib/python2.7/site-packages/parsimonious/expressions.py", line 122, in parse
    raise IncompleteParseError(text, node.end, self)
parsimonious.exceptions.IncompleteParseError: Rule 'result' matched in its entirety, but it didn't consume all the text. The non-matching portion of the text begins with 'workspace_auto_back_' (line 29, column 1).
0 08:52 ~/ $ i3parse  --file .config/i3/config mode-graph
usage: i3parse [-h] {free,modes,mode-graph,validate,bindings} ...
i3parse: error: argument command: invalid choice: '.config/i3/config' (choose from u'free', u'modes', u'mode-graph', u'validate', u'bindings')
0 08:53 ~/ $ i3parse mode-graph --file .config/i3/config 
usage: i3parse [-h] {free,modes,mode-graph,validate,bindings} ...
i3parse: error: unrecognized arguments: --file
0 08:54 ~/ $ i3parse mode-graph 
Traceback (most recent call last):
  File "/bin/i3parse", line 11, in <module>
    load_entry_point('i3parse==0.1.0', 'console_scripts', 'i3parse')()
  File "/usr/lib/python2.7/site-packages/i3parse/i3parse.py", line 127, in main
    with open(args.file) as stream:
IOError: [Errno 2] No such file or directory: '/home/bhepple/.i3/config'
0 08:54 ~/ $ i3parse --help
usage: i3parse [-h] {free,modes,mode-graph,validate,bindings} ...

positional arguments:
  {free,modes,mode-graph,validate,bindings}
    free                Find free keys with certain properties
    modes               Show the keybinding modes and how to traverse them
    mode-graph          Show the keybinding modes and how to traverse them
    validate            Validate key-bindings file (check if it parses)
    bindings            Show bindings

optional arguments:
  -h, --help            show this help message and exit
`

**Comment by talwrii** [comment]
> i3parse free

I've added support for this calling style in 9fa04fb4d9844be2209128f7f62fbec4fdb8cbe1.

**Comment by talwrii** [comment]
May still be an issue, so reopening:

https://www.reddit.com/r/i3wm/comments/7nckbu/i3parse_now_finds_unbound_keybindings_for_your/ds3y7aa/

Awaiting feedback
